### ISSUE TITLE
Please explain what does svg tag do

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-aramei#3]
I stumbled upon this code in your html:
```html
<svg height="20" width="65">
  <line x1="0" y1="10" x2="65" y2="10" style="stroke:rgb(255,255,255);stroke-width:2" />
</svg>
```

Please tell me what do `svg` tag ?
What purpose of attributes `x1`,  `y1`,  `x2`,  `y2` for tag `line` ?

**Comment by aramei** [comment]
I use this code for both lines near star.

As i understand, svg in real time make vector graphic. So, x1, y1 is coordinates for first dot and x3, y2 for second dot which in sum make a line which i need in this Homework.

Also as i understand, for svg tag i set height and width, in which graphic will be made.

**Comment by eko24ive** [comment]
Indeed, I can see you get this topic
